name: CI/CD

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USERNAME }}
          KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          REPO: https://github.com/jimyungkoh/nest-board-api-server.git
        run: |
          mkdir -p ~/.ssh
          echo "$KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST '
            mkdir -p ~/nest-board-api-server
            cd ~/nest-board-api-server
            if [ ! -d .git ]; then
              git clone ${{ env.REPO }} .
            else
              git pull origin main
            fi
            npm install
            npm run build
            docker build -t nest-board-api-server .
            docker stop nest-board-api-server || true
            docker rm nest-board-api-server || true
            docker run -d --name nest-board-api-server \
              -p 80:3000 \
              -e SERVER_PORT="${{ env.SERVER_PORT }}" \
              -e DB_TYPE="${{ env.DB_TYPE }}" \
              -e DB_HOST="${{ env.DB_HOST }}" \
              -e DB_PORT="${{ env.DB_PORT }}" \
              -e DB_USERNAME="${{ env.DB_USERNAME }}" \
              -e DB_PASSWORD="${{ env.DB_PASSWORD }}" \
              -e DB_DATABASE="${{ env.DB_DATABASE }}" \
              -e DB_SYNCHRONIZE="${{ env.DB_SYNCHRONIZE }}" \
              -e BCRYPT_SALT_ROUNDS="${{ env.BCRYPT_SALT_ROUNDS }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e JWT_ACCESS_TOKEN_EXPIRES_IN="${{ env.JWT_ACCESS_TOKEN_EXPIRES_IN }}" \
              -e JWT_ACCESS_TOKEN_SECRET="${{ secrets.JWT_ACCESS_TOKEN_SECRET }}" \
              -e JWT_REFRESH_TOKEN_EXPIRES_IN="${{ env.JWT_REFRESH_TOKEN_EXPIRES_IN }}" \
              -e JWT_REFRESH_TOKEN_SECRET="${{ secrets.JWT_REFRESH_TOKEN_SECRET }}" \
              -e AWS_S3_REGION="${{ env.AWS_S3_REGION }}" \
              -e AWS_S3_ACCESS_KEY_ID="${{ secrets.AWS_S3_ACCESS_KEY_ID }}" \
              -e AWS_S3_SECRET_ACCESS_KEY="${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}" \
              -e AWS_S3_BUCKET_NAME="${{ env.AWS_S3_BUCKET_NAME }}" \
              -e NANOID_LENGTH="${{ env.NANOID_LENGTH }}" \
              nest-board-api-server
          '
